import { IGRPMenuProps } from '@/features/menus/types';

export const IGRP_DEFAULT_MENU: IGRPMenuProps[] = [
  {
    id: 1,
    name: 'Configurações',
    type: 'FOLDER',
    position: 1,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: null,
    parentId: null,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
  {
    id: 2,
    name: 'Tipo de Serviços',
    type: 'MENU_PAGE',
    position: 2,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/tipos-servicos',
    parentId: 1,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
  {
    id: 3,
    name: 'Status de Pedidos',
    type: 'MENU_PAGE',
    position: 2,
    icon: 'UserCog',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/status-pedidos',
    parentId: 1,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
  {
    id: 4,
    name: 'Categorias',
    type: 'MENU_PAGE',
    position: 2,
    icon: 'Users',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/categorias',
    parentId: 1,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  }
];
